<!--Formulario Cadastro-->
<section class="container-fluid px-5  bg-sky">
    <div class="row">
        <div class="col-md-6">
            <div class="greeting__container">
                <h1>DevPub</h1>
                <h3>Comunidade para desenvolvedores
                    <p class="h3">Pra você que é <span class="typewrite" data-period="2000" data-type='["Fullstack", "Front-End", "Back-End","Quality Assurance","DevOps","Viado"]'>Viado</span></p>
                </h3>

            </div>
        </div>
        <div class="col-md-6">
            <section class="pt-5 w-100 d-flex justify-content-around">
                <div id="cadastro" class="pb-5 w-100 d-flex flex-column justify-content-around h-100">
                        <form method="post" action="/registerUser" class="d-flex flex-column align-items-center w-100">
                            <h2 class="m-0">Cadastro</h2>
                            <hr>
                            <div class="grupo_form form-group w-100 justify-content-around px-3">
                            <? if (isset($_GET['registerError']) && $_GET['registerError'] == 6) { ?>
                                    <p class="alert-danger text-center">* Usuário já existente *</p>
                            <? } ?>
                                <? if (isset($_GET['registerError']) && $_GET['registerError'] == 1) { ?>
                                    <p class="alert-danger text-center">* Nome não informado</p>
                                <? } ?>
                                <input type="text" name="name" placeholder="Nome:" class="form-control form-control-sm my-2" autofocus>

                                <? if (isset($_GET['registerError']) && $_GET['registerError'] == 2) { ?>
                                    <p class="alert-danger text-center">* Email não informado</p>
                                <? } ?>
                                <input type="email" name="email" placeholder="E-mail:" class="form-control form-control-sm my-2">


                                <? if (isset($_GET['registerError']) && $_GET['registerError'] == 4) {
                                ?>
                                    <p class="alert-danger text-center">* Senha não informada</p>
                                <? } ?>
                                <? if (isset($_GET['registerError']) && $_GET['registerError'] == 5) {
                                    $border = true;
                                ?>
                                    <p class="alert-danger text-center">* Senhas não coincidem</p>
                                <? } ?>
                                    <input type="password" name="senha" id="password" placeholder="Senha:" class="form-control form-control-sm my-2">

                                    <input type="password" name="confirmaSenha" id="passwordConfirm" placeholder="Confirme sua Senha:" class="form-control form-control-sm my-2">

                                <h4 class="py-2 text-center">Área de Interesse</h4>
                                <? if (isset($_GET['registerError']) && $_GET['registerError'] == 1) { ?>
                                    <p class="alert-danger text-center">* Área de Interesse não informada</p>
                                <? } ?>


                                <div class="d-flex justify-content-between flex-wrap form-check">

                                    <? foreach ($this->view->desire as $item) { ?>
                                        <div class="m-1">
                                            <input type="radio" class="btn-check" name="interest" id="interest<?= $item['id'] ?>" value="<?= $item['id'] ?>" autocomplete="off">
                                            <label class="btn btn-dark btn-outline-dark" for="interest<?= $item['id'] ?>" onclick=""><?= $item['desire'] ?></label>
                                        </div>
                                    <? } ?>
                                </div>

                            </div>

                            <hr>
                            <button class="btn btn-primary btn-lg w-75" type="submit">Cadastrar</button>
                            <hr>
                        </form>
                        <div class="d-flex justify-content-center">
                            <span class="btn btn-outline-warning w-50" id="switch">Entrar Conta</span>
                        </div>
                    </div>

                    <div id="login" class="pb-5 w-100 d-flex flex-column justify-content-around h-100 d-lg-none">
                        <form method="post" action="/loginUser" class="d-flex flex-column align-items-center w-100">
                            <h2 class="m-0">Login</h2>
                            <hr>
                            <div class="grupo_form form-group w-100 justify-content-around px-3">
                                <input type="email" name="email" placeholder="E-mail:" class="form-control form-control-sm my-2"> 
                                <input type="password" name="password" placeholder="Senha:" class="form-control form-control-sm my-2"> 
                            </div>  
                            <hr>
                            <button class="btn btn-primary btn-lg w-75" type="submit">Logar</button>
                            <hr>
                        </form>
                        <div class="d-flex justify-content-center">
                            <span class="btn btn-outline-danger w-50" id="switch">Criar uma Conta</span>
                        </div>
                    </div>

            </section>
        </div>
    </div>

    <script src="assets/js/passwordFeedback.js"></script>
    <script src="assets/js/typewriter.js"></script>
    <script src="assets/js/formsSwitcher.js"></script>
    </div>
</section>