<section class="bg-sky">
        <div class="container bg-light p-5 py-5 h-100">
            <div class="row">
                <div class="col-md-4 text-sm-center mb-sm-2 mt-sm-0">
                    <img src="/Imagens/eduardi.jpeg" alt="Foto do Estudante" class="img-thumbnail bg-secondary rounded">
                </div>
                <div class="col-md-8">
                    <h2><?= $this->view->dadosUsuario->nome ?></h2>
                    <p>Data de Criação: 15/06/2024</p>
                    <p>Ultima Sessão: 00</p>
                    <p>Email: <?= $this->view->dadosUsuario->email ?></p>
                    <p>Area de Interesse: <span class="text-info"><?= $this->view->dadosUsuario->interesse ?></span></p>
                </div>
            </div>

            <hr>
    </section>