<section id="materiais_lista" class="pb-5 pt-3">

    <div class="container text-center">

      <div class="row mt-1 justify-content-between">

        <div class="col-12">
          <hr>

          <h1 class="display-1 mb-0">Front-End</h1>

          <hr>
        </div>
        <div class="col-12 d-flex justify-content-md-between flex-wrap">
          <div class="col-md-4 col-sm-12">

            <div class="card card-borda mx-auto" style="width: 22rem;">
              <div class="card-img-top card-imagem text-right" style="background-image:url('assets/imgs/prototipação/HTML.jpg');"
                alt="HyperText Markup Language">
              </div>
              <div class="card-body divisa text-light"
                style="background: radial-gradient(rgb(240, 162, 46),rgb(255, 115, 0));">
                <h5 class="card-title card_titulo">HTML</h5>
                <p class="card-text">HyperText Markup Language ou HTML, é a ferramenta que você irá utilizar para criar
                  a
                  estrutura do seu site.</p>
                <a href="/html" class="btn btn-outline-light">Go somewhere</a>
              </div>
            </div>

          </div>

          <div class="col-md-4 col-sm-12">

            <div class="card card-borda  mx-auto" style="width: 22rem;">
              <div class="card-img-top card-imagem" style="background-image:url('assets/imgs/prototipação/CSS.png');"
                alt="Cascading Style Sheet"></div>
              <div class="card-body divisa text-light"
                style="background: linear-gradient(to bottom, rgb(119, 119, 243), rgb(119, 193, 218));">
                <h5 class="card-title card_titulo">CSS</h5>
                <p class="card-text">HyperText Markup Language ou HTML, é a ferramenta que você irá utilizar para criar
                  a
                  estrutura do seu site.</p>
                <a href="/css" class="btn btn-outline-light">Go somewhere</a>
              </div>
            </div>

          </div>

          <div class="col-md-4 col-sm-12 ">

            <div class="card card-borda mx-auto" style="width: 22rem;">
              <div class="card-img-top card-imagem" style="background-image:url('assets/imgs/prototipação/Bootstrap.png');"
                alt="Bootstrap"></div>
              <div class="card-body divisa text-light"
                style="background: linear-gradient(to bottom, rgb(102, 35, 228), rgb(209, 119, 245));">
                <h5 class="card-title card_titulo">Bootstrap</h5>
                <p class="card-text">HyperText Markup Language ou HTML, é a ferramenta que você irá utilizar para criar
                  a
                  estrutura do seu site.</p>
                <a href="/bootstrap" class="btn btn-outline-light">Go somewhere</a>
              </div>
            </div>

          </div>

        </div>
        <div class="col-12 d-flex justify-content-md-around flex-wrap">
          <div class="col-md-4 col-sm-12">

            <div class="card card-borda mx-auto" style="width: 22rem;">
              <div class="card-img-top card-imagem" style="background-image:url('assets/imgs/prototipação/angular.png');">
              </div>
              <div class="card-body divisa text-danger">
                <h5 class="card-title card_titulo">Angular</h5>
                <p class="card-text">HyperText Markup Language ou HTML, é a ferramenta que você irá utilizar para criar
                  a
                  estrutura do seu site.</p>
                <a href="/angular" class="btn btn-outline-danger">Go somewhere</a>
              </div>
            </div>

          </div>

          <div class="col-md-4 col-sm-12">

            <div class="card card-borda mx-auto" style="width: 22rem;">
              <div class="card-img-top card-imagem" style="background-image:url('assets/imgs/prototipação/Sass.png');">
              </div>
              <div class="card-body divisa text-light"
                style="background: linear-gradient(to bottom, rgb(216, 76, 186), #DAA);">
                <h5 class="card-title card_titulo">Sass</h5>
                <p class="card-text">HyperText Markup Language ou HTML, é a ferramenta que você irá utilizar para criar
                  a
                  estrutura do seu site.</p>
                <a href="/sass" class="btn btn-outline-light">Go somewhere</a>
              </div>
            </div>

          </div>

          <div class="col-md-4 col-sm-12">

            <div class="card card-borda mx-auto" style="width: 22rem;">
              <div class="card-img-top card-imagem" style="background-image:url('assets/imgs/prototipação/react.png');">
              </div>
              <div class="card-body divisa text-light"
                style="background: linear-gradient(140deg, rgb(103, 215, 252), rgb(109, 170, 219));">
                <h5 class="card-title card_titulo sombra">React</h5>
                <p class="card-text sombra">HyperText Markup Language ou HTML, é a ferramenta que você irá utilizar para
                  criar a estrutura do seu site.</p>
                <a href="/react" class="btn btn-outline-light">Go somewhere</a>
              </div>
            </div>

          </div>
        </div>

      </div>

      <div class="row mt-3">
        <div class="col-12">
          <hr>
          <h1 class="display-1 mb-0">Back-End</h1>
          <hr>
        </div>
        <div class="col-12 d-flex justify-content-md-around flex-wrap">
          <div class="col-md-4 col-sm-12">

            <div class="card card-borda mx-auto" style="width: 22rem;">
              <div class="card-img-top card-imagem" style="background-image:url('assets/imgs/prototipação/sql.png');">
              </div>
              <div class="card-body divisa" style="color:orangered;">
                <h5 class="card-title card_titulo">SQL</h5>
                <p class="card-text">HyperText Markup Language ou HTML, é a ferramenta que você irá utilizar para criar
                  a
                  estrutura do seu site.</p>
                <a href="/sql" class="btn sql">Go somewhere</a>
              </div>
            </div>

          </div>

          <div class="col-md-4 col-sm-12">

            <div class="card card-borda mx-auto" style="width: 22rem;">
              <div class="card-img-top card-imagem" style="background-image:url('assets/imgs/prototipação/python.png');">
              </div>
              <div class="card-body divisa" style="color:#FFF; background-color:#00304D;">
                <h5 class="card-title card_titulo"><span style="color:#00ACE8">Pyt</span><span
                    style="color:#EDD046">hon</span></h5>
                <p class="card-text">HyperText Markup Language ou HTML, é a ferramenta que você irá utilizar para criar
                  a
                  estrutura do seu site.</p>
                <a href="/python" class="btn py">Go somewhere</a>
              </div>
            </div>

          </div>

          <div class="col-md-4 col-sm-12">

            <div class="card card-borda mx-auto" style="width: 22rem;">
              <div class="card-img-top card-imagem" style="background-image:url('assets/imgs/prototipação/csharp.png');">
              </div>
              <div class="card-body divisa text-light"
                style="background:linear-gradient(155deg,#B077F8,#B077F8,#291955,#291955);">
                <h5 class="card-title card_titulo">C-Sharp / C#</h5>
                <p class="card-text">HyperText Markup Language ou HTML, é a ferramenta que você irá utilizar para criar
                  a
                  estrutura do seu site.</p>
                <a href="/csharp" class="btn btn-outline-light">Go somewhere</a>
              </div>
            </div>

          </div>
        </div>
        <div class="col-12 d-flex justify-content-md-around flex-wrap">
          <div class="col-md-4 col-sm-12">

            <div class="card card-borda mx-auto" style="width: 22rem;">
              <div class="card-img-top card-imagem" style="background-image:url('assets/imgs/prototipação/php.png');">
              </div>
              <div class="card-body divisa text-light" style="background:#556594;">
                <h5 class="card-title card_titulo">PHP</h5>
                <p class="card-text">HyperText Markup Language ou HTML, é a ferramenta que você irá utilizar para criar
                  a
                  estrutura do seu site.</p>
                <a href="/csharp" class="btn btn-outline-light">Go somewhere</a>
              </div>
            </div>

          </div>

          <div class="col-md-4 col-sm-12">

            <div class="card card-borda mx-auto" style="width: 22rem;">
              <div class="card-img-top card-imagem" style="background-image:url('assets/imgs/prototipação/java.png');">
              </div>
              <div class="card-body divisa text-light" style="background:#EB2D2F;">
                <h5 class="card-title card_titulo">Java</h5>
                <p class="card-text">HyperText Markup Language ou HTML, é a ferramenta que você irá utilizar para criar
                  a
                  estrutura do seu site.</p>
                <a href="/java" class="btn btn-outline-light">Go somewhere</a>
              </div>
            </div>

          </div>

          <div class="col-md-4 col-sm-12">

            <div class="card card-borda mx-auto" style="width: 22rem;">
              <div class="card-img-top card-imagem" style="background-image:url('assets/imgs/prototipação/JS.png');"></div>
              <div class="card-body divisa text-dark" style="background:#FFE719;">
                <h5 class="card-title card_titulo">Java</h5>
                <p class="card-text">HyperText Markup Language ou HTML, é a ferramenta que você irá utilizar para criar
                  a
                  estrutura do seu site.</p>
                <a href="/javascript" class="btn btn-outline-dark">Go somewhere</a>
              </div>
            </div>

          </div>
        </div>
      </div>

    </div>

  </section>

