<section>
        <div class="container bg-light p-5 py-5 h-100">
            <div class="row">
                <div class="col-md-4 text-center h-100">
                    <img src="assets/imgs/eduardi.jpeg" alt="Foto do Estudante" class="img-thumbnail bg-secondary rounded">
                </div>
                <div class="col-md-8 alert alert-secondary h-100 my-auto">
                    <h2 class="alert alert-dark text-dark"><?= $_SESSION['name'] ?></h2>
                    <p class="border-bottom border-dark pb-2 mt-0">Data de Criação: <?= $_SESSION['data_criacao'] ?></p>
                    <p class="border-bottom border-dark pb-2 mt-0">Ultima Sessão: <?= $_SESSION['ultima_sessao'] ?></p>
                    <p class="border-bottom border-dark pb-2 mt-0">Email: <?= $_SESSION['email'] ?></p>
                    <p class="border-bottom border-dark pb-2 mt-0">Area de Interesse: <span class="badge badge-info"><?= $_SESSION['desire'] ?></span></p>
                </div>
            </div>
</section>