<!DOCTYPE html>
<html>
    <head>

        <meta charset="utf-8" />
        <title>Devpub - <?= ucfirst($this->view->page); ?></title>

        <!-- Meta tags Obrigatórias -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Normalize CSS-->
        <link rel="stylesheet" href="assets/css/normalize.css">
        
        <!-- Bootstrap CSS -->
        <link 
            rel="stylesheet" 
            href="/assets/css/bootstrap-css/bootstrap.min.css">

        <!-- * Font Awesome * -->
        <link 
            rel="stylesheet" 
            href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">

        <!-- UIkit CSS -->
        <link 
            rel="stylesheet" 
            href="https://cdn.jsdelivr.net/npm/uikit@3.21.16/dist/css/uikit.min.css" />

        <!--CSS Personalizado-->
        <link rel="stylesheet" href="assets/css/style.css">
        <link rel="stylesheet" href="assets/css/landing.css">
        <link rel="stylesheet" href="assets/css/cadastro.css">
        
        <link rel="icon" href="assets/imgs/logos/Logo.png">

        <!--Jquery JS-->
        <script 
                src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
                crossorigin="anonymous">
            </script>


    </head>

    <body class="bg-sky">
        
        <!--Cabeçalho-->
        <header class="sticky-top header__container">

            <nav class="navbar navbar-expand-sm navbar-light navega" style="max-height:307.6px;">
                <div class="container d-flex justify-content-between">
                    <!--Logo Site-->
                    <a href="./home" class="navbar-brand p-1 rounded alert alert-info my-auto navbar__index-link">
                        <img src="./assets/imgs/logos/NavbarLogo.png" class="navbar__logo w-100">
                    </a>
                </div>

            </nav>
        </header>

        <!--Conteudo-->
        <div class="content__container w-100 h-auto">
            <?= $this->content() ?>
        </div>

        <!--Rodapé-->
        <footer class="container-fluid py-3 border-top mt-5 bg-light">
            <div class="row">
                <div class="col mb-3">
                    <a href="/" class="d-flex align-items-center mb-3 link-body-emphasis text-decoration-none">
                        <svg class="bi me-2" width="40" height="32">
                            <use xlink:href="#bootstrap"></use>
                        </svg>
                    </a>
                    <p class="text-body-light">© 2024 DevPub</p>
                </div>

                <div class="col mb-3">
                    <h5>Section</h5>
                    <ul class="nav">
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
                    </ul>
                </div>

            </div>
        </footer>

            
            <!--Popper JS-->
            <script 
                src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
                integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" 
                crossorigin="anonymous">
            </script>

            <!--Bootstrap JS-->
            <script 
                src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
                integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" 
                crossorigin="anonymous">
            </script>

            <!-- UIkit JS -->
            <script 
                src="https://cdn.jsdelivr.net/npm/uikit@3.21.16/dist/js/uikit.min.js">
            </script>
            <script 
                src="https://cdn.jsdelivr.net/npm/uikit@3.21.16/dist/js/uikit-icons.min.js">
            </script>
    </body>

</html>