<html>
<head>

    <meta charset="utf-8" />
    <title>Miniframework</title>

    <!-- Meta tags Obrigatórias -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- * Font Awesome * -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">

    <!--CSS Personalizado-->
    <link rel="stylesheet" href="style.css">
    <link rel="icon" href="assets/imgs/icone.jpg">

</head>

<body>
    <!--Fazer Inclusão do Layout-->
    <!--Cabeçalho-->
    <header class="sticky-top">

        <nav class="navbar navbar-expand-sm navbar-light navega" style="overflow-y:visible; max-height:307.6px;">
            <div class="container d-flex justify-content-between">
                <!--Logo Site-->
                <a href="./" class="navbar-brand p-1 rounded alert alert-info my-auto">
                    <img src="assets/imgs/gej (2).png" width="60">
                    <span class="nav-brand text-dark mr-2">DevHub</span>
                </a>
                <!--<h2>Rainer</h2>-->
                <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse float-sm-left" id="nav-principal">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/materiais">Materiais</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/equipe">Equipe</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/intro">Sobre nós</a>
                        </li>

                        <li class="nav-item">
                            <?php

                            if ($_SESSION['autenticado'] == true) {
                                echo '<div class="dropdown usuarioFeed float-right">
                                            <button class="btn btn-info bg-transparent rounded border-0 shadow-none" data-toggle="dropdown" type="button">
                                                <img src="assets/imgs/eduardi.jpeg" class="rounded-circle" width="50" height="50">
                                            </button>
                                            <div class="dropdown-menu bg-light float-sm-left" style="max-width:100px; z-index: 1000000 !important;">
                                                <a href="/usuario" class="dropdown-item">Conta</a>
                                                <a href="/contact" class="dropdown-item">Suporte</a>
                                                <div class="dropdown-divider"></div>
                                                <center>
                                                <a href="/logout" class="dropdown-item badge badge-danger w-50 h-50">Sair</a>
                                                </center>
                                            </div>
                                        </div> <div class="clearfix"></div>';
                            } else {
                                echo "<a href='/login' class='btn btn-light mt-3'><span class='text-secondary'>Entrar</span></a>";
                            }

                            ?>
                        </li>

                    </ul>
                </div>
            </div>

        </nav>
    </header>
    <?= $this->content() ?>
    
    <footer class="bg-dark">
        <h2>Caralho</h2>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
        </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous">
        </script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
        </script>
</body>

</html>